version: "2.4"
services:
  postgresql:
    image: postgres:12.4
    container_name: postgresql12
    ports:
      - "5432:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ${HOME}/docker_volumes/postgresql/12/pgdata:/var/lib/postgresql/data/pgdata
