version: "2.4"
services:
  openkm-db:
    image: postgres:12.4
    container_name: openkm-db
    ports:
      - "15432:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ${HOME}/docker_volumes/openkm-ce/pgdata:/var/lib/postgresql/data/pgdata

  openkm-ce:
    image: openkm/openkm-ce:6.3.9
    container_name: openkm-ce
    ports:
      - "8090:8080"
    volumes:
      - ${PWD}/server.xml:/opt/tomcat/conf/server.xml
      - ${PWD}/OpenKM.cfg:/opt/tomcat/OpenKM.cfg
      - ${HOME}/docker_volumes/openkm-ce/repository:/opt/tomcat/repository