version: "3.7"
services:
  sso:
    image: jboss/keycloak:12.0.3
    container_name: ${KEYCLOAK_CONTAINER_NAME}
    hostname: ${KEYCLOAK_HOST_NAME}
    ports:
      - "9080:8080"
      - "9443:8443"
    environment:
      # KEYCLOAK_USER: ${KEYCLOAK_USER}
      # KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      DB_VENDOR: postgres
      DB_ADDR: ${DB_ADDR}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      # KEYCLOAK_WELCOME_THEME: is
      # KEYCLOAK_STATISTICS: db,http
      # JAVA_OPTS_APPEND: "-Dkeycloak.profile.feature.scripts=enabled"
    volumes:
      - ${DOCKER_VOLUME}/keycloak/themes/is:/opt/jboss/keycloak/themes/is
      - ${DOCKER_VOLUME}/keycloak/themes/indolabel:/opt/jboss/keycloak/themes/indolabel
      - ${DOCKER_VOLUME}/keycloak/deployments:/opt/jboss/keycloak/standalone/deployments
    networks:
      public:
      internal:

networks:
  public:
    external:
      name: public
  internal:
    external:
      name: internal
