version: "2.4"
services:
  server:
    image: jboss/keycloak:12.0.2
    container_name: keycloak
    hostname: ${KEYCLOAK_HOST_NAME}
    ports:
      - "9080:8080"
      - "9443:8443"
    environment:
      # KEYCLOAK_USER: ${KEYCLOAK_USER}
      # KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      DB_VENDOR: postgres
      DB_ADDR: postgresql:5432
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      # KEYCLOAK_WELCOME_THEME: is
      # KEYCLOAK_STATISTICS: db,http
      # JAVA_OPTS_APPEND: "-Dkeycloak.profile.feature.scripts=enabled"
    volumes:
      - ${HOME}/docker_volumes/keycloak/themes/is:/opt/jboss/keycloak/themes/is
      - ${HOME}/docker_volumes/keycloak/themes/indolabel:/opt/jboss/keycloak/themes/indolabel
      - ${HOME}/docker_volumes/keycloak/deployments:/opt/jboss/keycloak/standalone/deployments

networks:
  default:
    external:
      name: backend
