version: "3.7"
services:
  pgsrv01:
    image: postgres:13.1
    container_name: ${POSTGRES_CONTAINER_NAME}
    hostname: ${POSTGRES_HOST_NAME}
    ports:
      - "5432:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ${HOME}/docker_volumes/postgresql/13/pgdata:/var/lib/postgresql/data/pgdata

networks:
  default:
    external:
      name: internal